### ISSUE TITLE
タスクはファイル分けた方がよい？

### ISSUE THREAD

**Issue by takumifukasawa** [kayac/kayac-html5-starter#23]
もし今後タスク増やす場合はgulpfileが肥大化しそうなので `gulp/tasks/` あたりに分割していった方がよいかも。

**Comment by hystking** [comment]
逆に1ファイルで見通しがいいぐらいのタスク数にしたい

**Comment by hystking** [comment]
@takumifukasawa 
これ閉じてもいいですか

**Comment by takumifukasawa** [comment]
閉じても大丈夫です。
@hystking @gon
