### ISSUE TITLE
how can I rename the filename?

### ISSUE THREAD

**Issue by baermowei** [kayac/kayac-html5-starter#44]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! myweb-demos@0.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myweb-demos@0.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myweb-demos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myweb-demos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myweb-demos
npm ERR! There is likely additional logging output above.

**Comment by nabettu** [comment]
did you do "npm install" before?

**Comment by baermowei** [comment]
yes ,and I try 'yarn install '

**Comment by hystking** [comment]
Sorry, Windows is not supported.
